### ISSUE TITLE
Not working on rPi2

### ISSUE THREAD

**Issue by rodcar125** [benjamind/gpio-json-server#1]
Hi!

I downloaded the gpio-json-server and after running it im able to connect to my pi2 through chilipeppr.com/grbl but when i try to add pins through chillipeppr i get nothing. I reviewed the log and this is what i get...

pi@S3RPi ~ $ gpio-json-server 
2015/06/18 04:25:54 main.go:91: Version:1.1
2015/06/18 04:25:54 main.go:98: Started server and websocket on 192.168.100.19:8888
2015/06/18 04:25:54 main.go:100: The GPIO JSON Server is now running.
2015/06/18 04:25:54 main.go:101: If you are using ChiliPeppr, you may go back to it and connect to this server using the GPIO widget.
2015/06/18 04:25:54 main.go:145: Reading prexisting pinstate file : pinstates.json
2015/06/18 04:44:27 conn.go:42: Started a new websocket handler
2015/06/18 04:44:27 hub.go:122: getpinmap
2015/06/18 04:44:27 hub.go:122: getpinstates
2015/06/18 04:44:27 hub.go:95: Error: embd: your host ": ARMv7 Processor rev 5 (v7l)" is not supported at this moment. request support at https://github.com/kidoman/embd/issues
2015/06/18 04:45:14 hub.go:122: initpin null pwm down testpin
2015/06/18 04:45:14 hub.go:95: Error: embd: your host ": ARMv7 Processor rev 5 (v7l)" is not supported at this moment. request support at https://github.com/kidoman/embd/issues

is this a rPi2 error related?
Thanks!

Rod

**Comment by benjamind** [comment]
You may need to change or update embd to support the pi2, it has a version
check that tests for a particular string to ensure support. I'm guessing
that string is different on a pi2. Unfortunately I do not have one to try
it out on. File a ticket on the embd repository, perhaps someone there can
help.

**Comment by rodcar125** [comment]
I have checked and i have version 0.1.0 which i think its the latest. I think embd its running ok because when i run the ./simpleblinker program that comes with the installation instructions of the embd runs fine.

sorry if i dont understand, i have basic knowledge at this. Does your program check for embd version and thats where im getting the error in the hub.go file?

Thanks for your help (:
Rod

**Comment by benjamind** [comment]
Oh it might just need recompilation. You're running gpio-json-server from binary not from the source?

**Comment by rodcar125** [comment]
I dont know what you mean by binary and source lol but i just type on the terminal < /usr/local/bin/gpio-json-server> to start the server, hope this helps

**Comment by benjamind** [comment]
I just built a new version, try getting gpio-json-server again and running it again. It should show version 1.11 if you did it right, and if I did it right it should now work on rpi2. I hope. No guarantees though as I don't have one to test against.

**Comment by rodcar125** [comment]
Its working now! (:
Thank you so much for your time!

![fullsizerender](https://cloud.githubusercontent.com/assets/11842419/8246236/b17b29d4-1600-11e5-9dcb-d2a349a01263.jpg)

**Comment by benjamind** [comment]
Excellent, glad it worked!
